### ISSUE TITLE
Unclear error message when auto-detecting a module that does not support SLSC Switch in its NVMEM

### ISSUE THREAD

**Issue by mdcerna** [ni/niveristand-routing-and-faulting-custom-device#112]
**Describe the bug**
While configuring an SLSC Switch Module, we would like to be able to click on the Autodetect button in order to query the SLSC Switch module for its properties (Model, Resource, and Topology), and list of endpoints.  However, not all modules define the `/switches` area (or information in the legacy `/capabilities` format) in their NVMEM. For these modules, it is unclear how to proceed.

**To Reproduce**
1. Open a System Explorer session in Veristand, add an SLSC Chassis with a valid IP address.
2. In the Modules section, select the SLSC Switch for one slot that you know is populated with an SLSC Switch module that does not contain the `/switches` area, e.g. the first revision of the 1225x modules.
3. Select the newly-configured Slot # (SLSC Switch) in the left tree within the System Explorer.
4. Click on the Autodect button at the top and note the resulting error.

**Expected behavior**
On step 4, we expect the fields to be populated (Model Number, Resource Name, and Topology) to match the module in that slot. If it cannot be automatically populated, we expect a more helpful error message indicating how to proceed.

**Screenshots**
![image](https://user-images.githubusercontent.com/573497/66681042-83329f00-ec37-11e9-9752-099961997cc6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Veristand 2017+, with the Routing and Faulting as well as the SLSC Switch custom devices installed.

**Additional context**

**Comment by rtzoeller** [comment]
If we detect the module is present, we could potentially provide some enhanced workflows to help the user. For example, if we detect a 1225x module that is incompatible with SLSC Switch, we could offer to (or automatically) load the offline definition from disk.
