### ISSUE TITLE
Endpoint Aliases allow user-defined endpoints that don't exist in consumer CDs

### ISSUE THREAD

**Issue by jashnani** [ni/niveristand-routing-and-faulting-custom-device#123]
Not sure if this something that we need to address but reporting the behavior anyway. Let's discuss whether or not this is a bug.

You can currently type in a user-defined endpoint and save it to sys def:

![image](https://user-images.githubusercontent.com/29433053/67028076-57e4ff80-f0d0-11e9-9dc6-e436f73ac208.png)

**Comment by buckd** [comment]
This is the easiest way you can get empty strings in the Endpoint column. The only other way is to add an empty string to the list of string selections. We can do that, it just looks a little weird.

![image](https://user-images.githubusercontent.com/29306186/67094152-cbdae280-f178-11e9-8ec4-1a3c9635149e.png)

The other option is you always have to have a selection that is valid (i.e. that column can never be empty.

**Comment by jashnani** [comment]
The fix would likely be needed at config time letting the user know that endpoint is invalid/non-existent. This is a minor issue and the deployment and run-time experience is acceptable. Closing it has low ROI.
