### ISSUE TITLE
Selecting Endpoint Aliases and Endpoint Configuration sometimes gives Page Error

### ISSUE THREAD

**Issue by jashnani** [ni/niveristand-routing-and-faulting-custom-device#126]
I can't get it to reproduce every time but here's what I'm seeing.

![image](https://user-images.githubusercontent.com/29433053/67129046-30229400-f1c3-11e9-82ae-24a8245270ee.png)

![image](https://user-images.githubusercontent.com/29433053/67129195-868fd280-f1c3-11e9-9710-2a52535c198e.png)

**Comment by buckd** [comment]
The reproduction steps are to go between these two pages:
1. Create an SLSC Switch custom device.
2. Expand the SLSC Switch item so `Endpoint Configuration` is visible in the tree.
3. Create a Routing and Faulting custom device.
4. Click on the `Endpoint Aliases` page.
5. Click on the `Endpoint Configuration` page under the SLSC custom device. The page will be broken.

I believe this is related to either `UI Common.lvlib` or one of the scripting libraries being pulled into both `Configuration` LLBs. When switching between the pages located in different libraries, the common dependencies aren't correctly loading. If you switch to another page in the SLSC Switch custom device and then back to `Endpoint Configuration`, it should be fixed.

The failure also happens going the other way; `Endpoint Configuration` to `Endpoint Aliases`.
