### ISSUE TITLE
Routing Channel State selection is not persisted

### ISSUE THREAD

**Issue by jashnani** [ni/niveristand-routing-and-faulting-custom-device#127]
Routing Channel State selection is not persisted when you click away and come back to the channel tree item.

Also, selecting a State and then hitting Save caused the state selection to go back to the first item in the list.

**Reproduction Steps**

1. Create a Routing Channel with more than one state
2. Select the second state from 'State Name' drop-down
3. Click on some other item in the left-hand tree
4. Click back on the routing channel in question
5. Notice that state selection has gone back first state in the list

I found this to be inefficient when I was wanting to compare endpoint names in Routing Channel with those in SLSC Switch section.

**Comment by rtzoeller** [comment]
I prototyped a fix to this using temporary properties; by prefixing the property names with an underscore the value is not persisted to the XML but is kept in memory while editing.

We could use the code below to write the value and analogous code to read it back.
![image](https://user-images.githubusercontent.com/573497/68032105-fce40880-fc8a-11e9-9871-e89efd344e25.png)
