### ISSUE TITLE
Setting an invalid Routing Channel State hangs the Routing and Faulting CD

### ISSUE THREAD

**Issue by Karl-G1** [ni/niveristand-routing-and-faulting-custom-device#145]
**Describe the bug**
After configuring a Routing Channel and deploying the system definition, selecting a State Value that does not exist causes the heartbeat of the Routing and Faulting CD to hang.

**To Reproduce**
1. Configure a system with an actual SLSC chassis and switching hardware
2. Instantiate the SLSC Switch and R+F Custom Devices
3. Create a new routing channel
4. Deploy the system definition
5. Use a numeric control to increment the routing channel value from -1 to 0
6. See the R+F CD status code go to 1 and the heartbeat to stop incrementing

**Expected behavior**
Unclear; is this a recoverable state, or should this act as more of a warning?

**Screenshots**
![image](https://user-images.githubusercontent.com/31290917/67816127-fc732400-fa76-11e9-905b-7adbec58c7a4.png)

**Comment by rtzoeller** [comment]
I don't know this is a _bug_, persay, since it is very much intended behavior within the current engine; all errors cause the custom device to shut down.

Whether or not _that_ is acceptable behavior is a larger conversation.

**Comment by Karl-G1** [comment]
This is expected behavior as @rtzoeller mentioned, so closing this issue for now.
