### ISSUE TITLE
Allow editing state information from 'State-Value Table' tab

### ISSUE THREAD

**Issue by jashnani** [ni/niveristand-routing-and-faulting-custom-device#150]
This is an enhancement for the interactive case and can be prioritized accordingly.

What we have today for State-Value Table is helpful as it allows you to see all state names and their corresponding values in the same page. It would be even better if we allowed editing these two things in the same page as well, so the user doesn't have to go to each state individually and change respective information. I could see this being cumbersome for routing channels with lots of states (10+).

This is forward looking enhancement and doesn't necessarily need to be supported in the first release IMO.

**Comment by Karl-G1** [comment]
This was fixed in #187
