### ISSUE TITLE
Export/Import of SLSC Switch module doesn't correctly set possible connections

### ISSUE THREAD

**Issue by buckd** [ni/niveristand-routing-and-faulting-custom-device#158]
**Describe the bug**
When you export an SLSC Switch module and import that configuration to another slot, the `Possible Connections` property is not populated.

**To Reproduce**
1. Add an SLSC Switch module to a Chassis.
2. Autodetect or load from JSON to get a list of possible connections.
3. Export the configuration.
4. Add a new SLSC Switch module to the chassis.
5. Import the configuration to the new module.
6. Save the sysdef.
7. Open the sysdef in Notepad++ and see the `user.CD.Routing and Faulting.Possible Connections`.

**Expected behavior**
The list of possible connections should be the same as the what was possible for the original module.

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
This manifests itself by not allowing the user to configure any connections using the new module because it reports no valid possible endpoints for that module.

**Comment by rtzoeller** [comment]
This looks like an easy fix in the Advanced System Definition API. I'm putting together the changes now.

**Comment by rtzoeller** [comment]
This fix for this is up for review in https://github.com/NIVeriStandAdd-Ons/VeriStand-Addon-System-Definition-Utilities/pull/9.

**Comment by Karl-G1** [comment]
Tested this was fixed in the lasted 19.2 build. The list of possible connection elements isn't maintained between import/export, but this does not affect the functionality.
