### ISSUE TITLE
Exporting and Importing Configuration in JSON format

### ISSUE THREAD

**Issue by skthelimit** [ni/niveristand-routing-and-faulting-custom-device#190]
**Is your feature request related to a problem? Please describe.**
Routing and Faulting configuration through UI is easy to make mistakes because of the long list of configurations to make. To make matters a little more worse, it's not easy to diff system configuration file to make sure my changes are all done correctly.

**Describe the solution you'd like**
It would be great if I can export the config as JSON file so that I can update JSON file directly to configure the Routing and Faulting Custom Device then import it back to the sysdef later. In fact, I am working on generating sysdef file via .NET script but it is not possible to update the configuration through .NET. I thought about manipulating the dat file but looks like it is not a good idea because it is binary format.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by rtzoeller** [comment]
I am not sure that the import mechanism today is flexible enough to accomplish what you want; all of the internal properties are written from the data file directly to the system definition, so you'd need to know a lot about the property format to script it (and at that point you would likely just script the system definition directly).

Have you considered creating a LabVIEW application which parses the JSON you generate and then uses the Routing and Faulting and SLSC Switch LabVIEW scripting APIs to generate the system definition? This would allow you to generate the JSON in whatever format you prefer, and then use the native scripting APIs to act on that data. That way you do not need to know about the specific property formats the custom devices use to persist data.

**Comment by skthelimit** [comment]
I have not considered creating LabVIEW application but if it's the way to go I want to get started on that. Is there an example that I can start with? I am not familiar with writing Custom Devices but I know how to execute .NET API using LabVIEW and get the sysdef's root node reference. Now the question is (1) Which VIs in Routing and Faulting Custom Device allow me to configure Endpoint Aliases and (2) Which VIs allow me to specify state, source, destinations etc. Thank you for your support!

**Comment by rtzoeller** [comment]
Are you using a version of the custom devices installed via nipkg files (either manually from [this release](https://github.com/ni/niveristand-routing-and-faulting-custom-device/releases/tag/v19.2.0) or as part of the VeriStand install directly), or a version built from source? That will impact where the scripting examples and scripting APIs are located. If you are using a version installed through nipkg files (recommended), the examples should be available at `C:\Program Files (x86)\National Instruments\LabVIEW 20xx\examples\NI VeriStand Custom Devices\Routing and Faulting\`.

For scripting the Routing and Faulting custom device:

- `Configure Routing and Faulting Custom Device.vi`: Example that adds an instance of the Routing and Faulting custom device to a target, and adds routing channels to it. This example assumes all connections (source, destination, module) are known ahead of time.
- `Add States to Routing and Faulting Custom Device.vi`: Example that adds a state to an existing routing channel. This would be more useful if you had an existing instance of the Routing and Faulting custom device, and needed to modify it.

Unfortunately I do not believe we have any existing examples of scripting endpoint aliases, nor will the scripting API allow you to use aliases to configure the source/destination pairs (i.e. you will need to resolve aliases yourself during scripting). That said, it should be relatively straightforward to configure the endpoint aliases, using VIs like `Add Alias.vi` or `Add N Aliases.vi`.

Note that you will need to have configured the SLSC Switch custom devices ahead of time; this can be done either through the System Explorer, or using the scripting API. There are examples for scripting this as well: `Configure Modules from Hardware.vi` and `Configure Modules from Switches JSON.vi`, depending on whether the hardware is or is not available during scripting.

**Comment by skthelimit** [comment]
Thank you Ryan for your support. I installed nipkgs from this page. The examples helped to understand how I should use this API to accomplish what I want. I started working with Configure Modules from Hardware VI as a reference, which works fine but this VI only works if SLSC is connected to the network. Because I want to work on my scripts offline, this is a bit problematic. So offline scripting is my next step.

My SLSC device is called SET-2010, for which I do not have json file. Therefore, I first autodetect the module in slot1, then export the slot1 configuration into .dat file. Then want to use this whenever I want to do offline scriptings. That being said, this method works only when I import .dat manually. When I use the script (ImportExport.lvlib:Import Custom Device Configuration.vi) to import .dat into SLSC Custom Device, then it returns .NET error 1172. I am posting the error detail below in case you are interested. 

This is the detail:
Error 1172 occurred at Property Node (Arg :1) Error accessing property NationalInstruments.VeriStand.SystemStorage.BaseNodeType.ID, (System.ArgumentNullException: Key cannot be null.
Parameter name: key)

Possible reason(s):

LabVIEW: (Hex 0x494) A .NET exception occurred in an external assembly. For information about correcting this error, copy the following exception (in bold), and search the Microsoft Developer Network (MSDN) Web site or the Web for a possible explanation.
System.ArgumentNullException in ImportExport.lvlib:Sysdef.SimpleImport.vi->ImportExport.lvlib:Import Custom Device Configuration.vi->test.vi

**Comment by rtzoeller** [comment]
I am not certain of the cause of the error you are seeing, but I suspect that the .NET assembly versions are getting mixed up somewhere along the way. If you let me know what version of VeriStand you are using, I can create a configuration file to try pinning those versions for your LabVIEW project.

Alternatively, you should be able to retrieve the JSON from the SET 2010 module relatively easily. I believe this hardware stores its switching configuration in the `/capabilities` section of NVMEM, which is easy to retrieve using the NI-SLSC API. Note that this is technically a legacy configuration which was not originally designed to work with NI-SLSC Switch, so other modules may place the switching configuration in a different section of NVMEM (`/switches`).

![image](https://user-images.githubusercontent.com/573497/82567222-b1b81700-9b42-11ea-8a51-632232fd4291.png)

You could then store that JSON in a file, and use code from the `Configure Modules from Switches JSON.vi` example to add them to a system definition.

**Comment by skthelimit** [comment]
Thank you JSON method works perfectly! By the way I have another problem. What would be the example arguments for ADD ALIAS VI?

**Comment by skthelimit** [comment]
Hi @rtzoeller , the problem has now been resolved by setting a full path starting with Targets/.. in the module path input. Thank you for your help!

**Comment by rtzoeller** [comment]
@skthelimit sorry for the delay on following up; I've been out of office. I'm glad you have been able to work around the issue.

Can you share which version of VeriStand you are using? I would like to investigate the .NET errors you were originally seeing.

**Comment by skthelimit** [comment]
@rtzoeller No problem at all! Thanks for your support. Veristand version I use is R3 f1.
