### ISSUE TITLE
API does not support executing as executable

### ISSUE THREAD

**Issue by skthelimit** [ni/niveristand-routing-and-faulting-custom-device#193]
**Describe the bug**
I noticed that when I build an executable using the Routing and Faulting API, I see errors and the script does not work properly even though I set file paths correctly (application level).

**To Reproduce**
1. Open the VI attached and run it. (Should work fine)
2. Put the VI into project then build it as executable then run it. It should error with code 7.

> Possible reason(s):
> 
> LabVIEW: (Hex 0x7) File not found. The file might be in a different location or deleted. Use the command prompt or the file explorer to verify that the path is correct.
> =========================
> Nonexistent GPIB interface.
> 
> VI Path: C:\Users\PXI\Desktop\Script Demo\builds\SLSC Sysdef Config\debug\vi.lib\NI VeriStand\Custom Device Offline API\NI VeriStand - Add Custom Device Section.vi
> 
> Built Application or Shared Library (DLL): Make sure all dynamically loaded VIs were properly included in the build specification for the application or shared library.
> 
> LabVIEW Real-Time: VIs built into executables cannot be accessed through VI Server calls. Use Source Distributions to dynamically call VIs on Real-Time targets.

**Expected behavior**
VI or EXE, the API should function correctly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Pharlap]

**Additional context**
[debug_main.vi.zip](https://github.com/ni/niveristand-routing-and-faulting-custom-device/files/4713817/debug_main.vi.zip)

**Comment by rtzoeller** [comment]
This looks like a known issue with the calling convention the VeriStand custom device API uses, and something I forgot to account for with my response to your other issue. The technical details of the issue are at the bottom of this message.


I see a few paths forward. The "easiest" one would be to avoid building the scripting application into a built app, and instead invoke the scripting in the LabVIEW development environment, as opposed to the LabVIEW runtime environment. **This can be done programmatically using the LabVIEW CLI.** For an example of executing a VI with arguments via the command line, see [here](https://zone.ni.com/reference/en-XX/help/371361R-01/lvconcepts/cli_predefined_operations/#RunVI).

If that solution doesn't work (i.e. if you will only have the LabVIEW runtime installed on the machine doing the scripting), there are some alternate workarounds we can investigate, but they will be potentially more involved than this one.

---

Technical details: The custom device API VIs attempt to find a corresponding internal VI in memory (if it has been loaded by VeriStand), and fall back to a path in VI.lib if they cannot find it (in the case of the LabVIEW development environment). Unfortunately, this calling convention is broken for built applications, as VI.lib no longer resolves to the standard location.

**Comment by skthelimit** [comment]
Thank you @rtzoeller . I also noticed that a VI uses a dynamic call of the VI by name. I thought this could be resolved by using Static VI reference, so the build process can include these dependency automatically. That being said, such implementation may exist across other VIs (even outside of this SLSC library) so fixing it may take some effort. For now LabVIEW CLI can be a solution but I would hope that it will be resolved in the future.

**Comment by Karl-G1** [comment]
Closing this bug due to it being a VeriStand API issue that is not unique to this Custom Device. We'll track internally the ability to do this.
