### ISSUE TITLE
Default Values in "Configure Routing and Faulting Custom Device" Need Updating

### ISSUE THREAD

**Issue by christinesparks** [ni/niveristand-routing-and-faulting-custom-device#222]
**Describe the bug**
The default value for Resource Name in Configure Routing and Faulting Custom Device.vi  in the connection list is "SLSC-12001-SN-Mod2". Given that the full path is required for the VI to function, it should be updated to "
Targets/Controller/SLSC/SLSC-12001-SN/Modules/Slot 2 (SLSC Switch)"

**To Reproduce**
1. Open the example VI
2. Observe the default values
3. Run the VI and get errors
4. Update to suggested values
5. Run the VI and don't get errors

**Expected behavior**
In-product documentation to help users use the example.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Pharlap]

**Additional context**

**Comment by rtzoeller** [comment]
@christinesparks do you know which version of R+F this was reported against? I believe this was actually already fixed by #182, which should have been included in the 20.0 release of the custom device.

**Comment by christinesparks** [comment]
@rtzoeller - it's possible I had cloned the code before that pull request was opened late Jan, so sounds like we're good!
