### ISSUE TITLE
release notes could be clearer

### ISSUE THREAD

**Issue by smithed180** [ni/niveristand-routing-and-faulting-custom-device#252]
**Is your feature request related to a problem? Please describe.**
The release notes say:

> The Routing and Faulting custom device and SLSC Switch custom device may be installed in any order and are the only packages required to perform routing and faulting in the VeriStand development environment.

However the terms used here don't correspond to the terms in the package list. Right now it says "you only need 2 which can be installed in any order, here are the 6 you can install and only in this order."

**Describe the solution you'd like**
Explain what each package is. This is especially true for the ones which may or may not write over things from VI Package Manager (if applicable).
Highlight the specific package names you need to install to get one of two goals: I want to use this in veristand, or I want to develop against this. 
Rename the packages to be more sensible. IE, don't use the term "support" when you mean "the custom device itself" in some cases, where "support" in other cases means "the files you need if you want to script the custom device".

Proposed readme:

Files necessary for end user running the custom device in veristand:
    custom-device-ni-routing-and-faulting-veristand-<version>_20.4.0.10_windows_x64.nipkg
-Provides the switch coordination custom device located under custom devices >> ni in VeriStand
    custom-device-ni-slsc-switch-veristand-<version>_20.4.0.10_windows_x64.nipkg
-Provides the SLSC module custom device which can be assigned to any SLSC slot in veristand to support onboard slsc-routing

Files needed for a user scripting the custom device
    common-custom-device-libraries-ni-veristand-<version>_20.4.0.10_windows_x64.nipkg
-Has libraries XYZ, conflicts with (and supercedes) VI Packages X, Y, and Z
    cd-scripting-ni-routing-and-faulting-veristand-<version>-20.4.0.10_windows_x64.nipkg
-Provides support for scripting the routing and faulting custom device from labview
    cd-scripting-ni-slsc-switch-veristand-<version>_20.4.0.10_windows_x64.nipkg
-Provides support for scripting the switch custom device from labview
    cd-scripting-examples-ni-routing-and-faulting-veristand-<version>_20.4.0.10_windows_x64.nipkg
-Provides examples for how to use the above two packages

**Comment by Karl-G1** [comment]
Addressed with the [20.5 release](https://github.com/ni/niveristand-routing-and-faulting-custom-device/releases/tag/v20.5.0) posting. The new table shows a clearer picture of what each package includes, and shows that technically all packages besides the Routing and Faulting Custom Device are optional, although you would need at least one 'hardware' custom device to make it usable.

Note that it is not as verbose as the changes requested here, and changing package names was also deferred.
