### ISSUE TITLE
Race condition on SLSC Switch consumer shutdown

### ISSUE THREAD

**Issue by buckd** [ni/niveristand-routing-and-faulting-custom-device#37]
**Describe the bug**
It's possible that the SLSC Switch engine will handle the VeriStand Shutdown event before the Routing and Faulting engine's producer can send the **Disconnect All* message. In this case, when the system definition is undeployed, existing switch connections may remain when they should not.

**To Reproduce**
None really. It's not very likely that the consumer would be handling a message and take long enough that a user could undeploy the system and get the shutdown event before the check happens, but it is a possibility.

**Expected behavior**
Only the Producer should be able to shut down the consumer loop. The check for the Shutdown notification in the consumer loop should be removed.

**Screenshots**
![image](https://user-images.githubusercontent.com/29306186/64040866-9542fd00-cb23-11e9-8d7c-7524cb27223b.png)
Remove the notification check and just block until the consumer gets the shutdown message from the producer.

**Desktop (please complete the following information):**
 - OS: All

**Additional context**
The check in the middle loop (writing status channels) should remain.

**Comment by rtzoeller** [comment]
@csjall by removing the Disconnect All message from being sent during shutdown, have we worked around this? The remaining call to send the Shutdown message has a timeout, so it should not block indefinitely.

**Comment by buckd** [comment]
Yes. Since the consumer shutdown now handles reset, this should be resolved.
