### ISSUE TITLE
Don't persist connect and disconnect messages beyond their required lifetime

### ISSUE THREAD

**Issue by rtzoeller** [ni/niveristand-routing-and-faulting-custom-device#41]
Filing in response to https://github.com/ni/niveristand-routing-and-faulting-custom-device/pull/36#issuecomment-527585569, https://github.com/ni/niveristand-routing-and-faulting-custom-device/pull/36#issuecomment-527492878.

We should not store the connect and disconnect messages in the engine data. Instead, we should pass them as a second argument.

**Comment by csjall** [comment]
Fixed with e182b818b115bff88c9d0c029f2a0c2c87268e8d
