### ISSUE TITLE
Improve default values for Add Routing Channel

### ISSUE THREAD

**Issue by jashnani** [ni/niveristand-routing-and-faulting-custom-device#53]
Based on the discussion today between @csjall, @mdcerna and @rtzoeller , we've agreed to change the scripting API in the following way:

Add the following default values to `Add Routing Channel`:

1. Default value for 'States and Connections List' should contain a state called 'No Connections' with a value -1.
2. Default value for Initial State should be 'No Connections' (referring the default state that will get created)

**Comment by mdcerna** [comment]
Fixed in PR #62
