### ISSUE TITLE
System Explorer experience feedback

### ISSUE THREAD

**Issue by jashnani** [ni/niveristand-routing-and-faulting-custom-device#70]
I’ve been testing the System Explorer experience and it looks pretty good. Had some review comments. Let me know what you think.

1. Add Description field to State (State Configuration tab) and move Routing Channel Description to its own row. Something like this:

![image](https://user-images.githubusercontent.com/29433053/65278834-8c29c800-daf2-11e9-8135-a976ea96e97f.png)

2. In State-Value Table, change label from ‘State’ to ‘State Name’
	 
Minor cosmetic feedback (not depicted in screenshot above but exists in product):

3. Source and Destination labels are further away from indicators 
4. Some labels are slightly indented. For example,  Routing Channel Name, Description, State 
Name, etc.
5. Endpoint configuration drop-downs appear enabled (as opposed to Topology where they look disabled).

**Comment by mdcerna** [comment]
> 1 and 2

Good ideas we should implement.

> 3, 4

Need clarification here, specify indented relative to what other object?

> 5\. Endpoint configuration drop-downs appear enabled (as opposed to Topology where they look disabled).

This appears to be the result of the Endpoint configuration indicator is populated with items (Load, Source, Configuration) whereas the topology has no items, though we are writing a string to its value. I would skip this slight difference (and the indicators are indeed both disabled).
