### ISSUE TITLE
Example silently fails if Routing and Faulting section exists

### ISSUE THREAD

**Issue by csjall** [ni/niveristand-routing-and-faulting-custom-device#73]
**Describe the bug**
While running `Scripting Examples\Configure Routing and Faulting Custom Device.vi` I ran into a weird issue. The example ran without error but it did not add the routing channels to the system definition.

**To Reproduce**
1. Create a new system definition in VeriStand
1. Add a Routing and Faulting custom device in System Explorer
1. Save the system definition file
1. Run the example `Scripting Examples\Configure Routing and Faulting Custom Device.vi` using the saved system definition file
1. Open the system definition file and notice the lack of channels

**Expected behavior**
I was expecting to see my routing channels added to the Routing and Faulting Custom Device. Alternatively I would expect an error saying that the Routing and Faulting Custom Device already exists.

**Comment by mdcerna** [comment]
Will be fixed by PR #75
